services:
  classifiation-api:
    container_name: classifiation
    build: .
    user: root
    environment:
      DICTIONARY_FILE:
      LANGUAGE: es
    ports:
      - 8002:8002
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true
    command: flask run --host=0.0.0.0 --port=8002

networks:
  default:
    name: cogstack-net
    external: true
